POST http://localhost:5000/register HTTP/1.1
content-type: application/json

{
    "name": "Algo",
    "lastname": "Ejemplo",
    "email": "estoes@ejemplo.com",
    "pass": "ABC123"
}

###

POST http://localhost:5000/login HTTP/1.1
content-type: application/json

{
    "email": "algo@ejemplo.com",
    "pass": "123456"
}
