-- MySQL Script generated by MySQL Workbench
-- Mon Mar  6 14:49:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbayd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbayd` ;

-- -----------------------------------------------------
-- Schema dbayd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbayd` DEFAULT CHARACTER SET utf8 ;
USE `dbayd` ;

-- -----------------------------------------------------
-- Table `dbayd`.`actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbayd`.`actor` ;

CREATE TABLE IF NOT EXISTS `dbayd`.`actor` (
  `idactor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `resumen` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `contrasena` VARCHAR(55) NOT NULL,
  `film_cast_idcast` INT NOT NULL,
  PRIMARY KEY (`idactor`),
  INDEX `fk_actor_film_cast1_idx` (`film_cast_idcast` ASC) VISIBLE,
  CONSTRAINT `fk_actor_film_cast1`
    FOREIGN KEY (`film_cast_idcast`)
    REFERENCES `dbayd`.`film_cast` (`idcast`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbayd`.`film_cast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbayd`.`film_cast` ;

CREATE TABLE IF NOT EXISTS `dbayd`.`film_cast` (
  `idcast` INT NOT NULL AUTO_INCREMENT,
  `movie_idmovie` INT NOT NULL,
  PRIMARY KEY (`idcast`),
  INDEX `fk_film_cast_movie1_idx` (`movie_idmovie` ASC) VISIBLE,
  CONSTRAINT `fk_film_cast_movie1`
    FOREIGN KEY (`movie_idmovie`)
    REFERENCES `dbayd`.`movie` (`idmovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbayd`.`film_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbayd`.`film_comment` ;

CREATE TABLE IF NOT EXISTS `dbayd`.`film_comment` (
  `idcomment` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(255) NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idcomment`),
  INDEX `fk_film_comment_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_film_comment_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `dbayd`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbayd`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbayd`.`movie` ;

CREATE TABLE IF NOT EXISTS `dbayd`.`movie` (
  `idmovie` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `director` VARCHAR(45) NOT NULL,
  `anio` VARCHAR(45) NOT NULL,
  `resumen` VARCHAR(255) NOT NULL,
  `poster` VARCHAR(100) NOT NULL,
  `promedio` INT NULL,
  `movie_rating_idrating` INT NOT NULL,
  `watchlist_idwatchlist` INT NOT NULL,
  `film_comment_idcomment` INT NOT NULL,
  PRIMARY KEY (`idmovie`),
  INDEX `fk_movie_movie_rating1_idx` (`movie_rating_idrating` ASC) VISIBLE,
  INDEX `fk_movie_watchlist1_idx` (`watchlist_idwatchlist` ASC) VISIBLE,
  INDEX `fk_movie_film_comment1_idx` (`film_comment_idcomment` ASC) VISIBLE,
  CONSTRAINT `fk_movie_movie_rating1`
    FOREIGN KEY (`movie_rating_idrating`)
    REFERENCES `dbayd`.`movie_rating` (`idrating`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_watchlist1`
    FOREIGN KEY (`watchlist_idwatchlist`)
    REFERENCES `dbayd`.`watchlist` (`idwatchlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_film_comment1`
    FOREIGN KEY (`film_comment_idcomment`)
    REFERENCES `dbayd`.`film_comment` (`idcomment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbayd`.`movie_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbayd`.`movie_image` ;

CREATE TABLE IF NOT EXISTS `dbayd`.`movie_image` (
  `idimage` INT NOT NULL AUTO_INCREMENT,
  `link_image` VARCHAR(255) NOT NULL,
  `movie_idmovie` INT NOT NULL,
  PRIMARY KEY (`idimage`),
  INDEX `fk_movie_image_movie1_idx` (`movie_idmovie` ASC) VISIBLE,
  CONSTRAINT `fk_movie_image_movie1`
    FOREIGN KEY (`movie_idmovie`)
    REFERENCES `dbayd`.`movie` (`idmovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbayd`.`movie_rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbayd`.`movie_rating` ;

CREATE TABLE IF NOT EXISTS `dbayd`.`movie_rating` (
  `idrating` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idrating`),
  INDEX `fk_movie_rating_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_movie_rating_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `dbayd`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbayd`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbayd`.`user` ;

CREATE TABLE IF NOT EXISTS `dbayd`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbayd`.`watchlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbayd`.`watchlist` ;

CREATE TABLE IF NOT EXISTS `dbayd`.`watchlist` (
  `idwatchlist` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idwatchlist`),
  INDEX `fk_watchlist_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_watchlist_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `dbayd`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
